apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
    name: demo-jte 
spec: 
    accessModes: 
        - ReadWriteOnce 
    resources: 
        requests: 
            storage: 1Gi 
        selector: 
            matchLabels: 
